### ISSUE TITLE
support latest version of stdlib

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/cem_issues#8]
## Use Case
I want to use cem with the latest version of stdlib

## Describe the Solution You Would Like
metadata.json states stdlib <9

## Describe Alternatives You've Considered
None. As the code is not public.

## Additional Context
Customer who update their modules on a regular basis want to be sure that cem is also working with latest version of stdlib.
Customers want to see compatibility within metadata.json and don't want to try-error.

**Comment by hsnodgrass** [comment]
We are going to officially support the latest versions of stdlib as of our next release for both modules. This release is scheduled to come out near term, but I'm not sure if I can give an exact date.
